--Создаем скрипт для занесения в таблицу Steps--
insert into Steps(StepName) values ('Айву вымыть, удалить сердцевину и нарезать небольшими кусочками.')
insert into Steps(StepName) values ('Айву разрезать, удалить сердцевину, нарезать крупными дольками. Половинку лимона разрезать на 4 части. Сложить в кастрюлю, влить 500 мл воды, довести до кипения и варить 20-30 минут до мягкости айвы.')
insert into Steps(StepName) values ('Аромата и вкуса водки не присутствует.')
insert into Steps(StepName) values ('В конце добавить измельченный чеснок.')
insert into Steps(StepName) values ('В отдельной посуде смешать муку и молоко до образования густой массы.')
insert into Steps(StepName) values ('В пакет положите сахар, соль и перец горошком.')
insert into Steps(StepName) values ('В процессе варки айва размягчится, образуется вкуснейший густой сироп.')
insert into Steps(StepName) values ('В процессе тушения посолить и посыпать смесью перцев.')
insert into Steps(StepName) values ('В сковороде разогреть сливочное масло, выложить айву и прогреть, постоянно перемешивая, в течение 5 минут.')
insert into Steps(StepName) values ('В течение 3-х дней по несколько раз в день мясо переворачивайте и встряхивайте пакет, чтобы оно равномерно промариновалось.')
insert into Steps(StepName) values ('В форму для выпечки помещаем заранее вырезанную пергаментную бумагу, предназначенную для выпечки.')
insert into Steps(StepName) values ('Варить айву в течение 1-1,5 часов, постоянно помешивая.')
insert into Steps(StepName) values ('Включаем режим «Тушение», время 1,5 часа. 6. После того, как прозвучит сигнал, добавляем мелко нарезанную зелень.')
insert into Steps(StepName) values ('Включить режим «Жарка», время 30 минут.')
insert into Steps(StepName) values ('Влить лимонный сок, посыпать сахаром, перемешать и готовить на среднем огне, помешивая, минут 10, чтобы сахар карамелизировался, а айва стала мягче.')
insert into Steps(StepName) values ('Влить теплое молоко, все перемешать.')
insert into Steps(StepName) values ('Возьмите пакет для замораживания продуктов, вставьте его в ёмкость, в которой будете мариновать мясо.')
insert into Steps(StepName) values ('Все вместе обжариваем.')
insert into Steps(StepName) values ('Все ингредиенты тщательно перемешиваем в специальной миске.')
insert into Steps(StepName) values ('Всыпать сахар, перемешать и поставить на средний огонь.')
insert into Steps(StepName) values ('Вымыть лимоны и айву')
insert into Steps(StepName) values ('Говядину порежьте на тонкие пластины и отбейте молоточком с обеих сторон.')
insert into Steps(StepName) values ('Горячий мармелад выложить в форму, лучше всего стеклянную или силиконовую, смазывать маслом или застилать бумагой не нужно. Оставить при комнатной температуре на 10-12 часов.')
insert into Steps(StepName) values ('Готовое тесто размещаем на вырезанный круг бумаги и раскатываем до концов окружности. Готовый круг из теста и бумаги размещаем в форме для выпечки и формируем бортики.')
insert into Steps(StepName) values ('Готовый пирог достать из духовки и остудить.')
insert into Steps(StepName) values ('Добавим чеснок в морковку.')
insert into Steps(StepName) values ('Для приготовления начинки нам понадобится: 5 яиц, 180 г. сахара, лимонный сок и щепотка соли, 2 ст. ложки муки и 3 ст. ложки молока, 900 г. творога, цедра 1 лимона.')
insert into Steps(StepName) values ('Для приготовления посыпки замороженное сливочное масло натереть на терке.')
insert into Steps(StepName) values ('Для теста основы нам понадобится: 200 г. муки (лучше просеянной), 65 г. сахара, 65 г. сливочного масла.')
insert into Steps(StepName) values ('Добавить муку, сахар и растолченные крупно орехи.')
insert into Steps(StepName) values ('Добавить порезанный мелко лук, обжарить вместе с мясом 3-4 минуты.')
insert into Steps(StepName) values ('Добавляем к мясу.')
insert into Steps(StepName) values ('Добавляем сахар, 0.5 ч.л. красного перца в морковь.')
insert into Steps(StepName) values ('Добавьте муку и еще раз хорошенько перемешайте.')
insert into Steps(StepName) values ('Добавьте немного сливочного масла на каждый блинчик.')
insert into Steps(StepName) values ('Добавьте сметану, перемешайте, прогрейте пару минут.')
insert into Steps(StepName) values ('Добавьте соду, сахар и соль')
insert into Steps(StepName) values ('Добавьте специи и посолите.')
insert into Steps(StepName) values ('Добавьте яичную смесь к мясу и хорошенько перемешайте.')
insert into Steps(StepName) values ('Довести варенье до кипения, помешивая айву, проварить 2 минуты и выключить.')
insert into Steps(StepName) values ('Довести до кипения, все время мешая.')
insert into Steps(StepName) values ('Долить воды.')
insert into Steps(StepName) values ('Если слишком быстро испарится вся жидкость, можно добавить немного воды или бульона.')
insert into Steps(StepName) values ('Если таковой нет, можно постараться нарезать.')
insert into Steps(StepName) values ('Жареный лаваш с начинкой подать в горячем виде.')
insert into Steps(StepName) values ('Желтки отделить от белков.')
insert into Steps(StepName) values ('Желтки смешать с сахаром, а белки взбить с лимонным соком и щепоткой соли до образования пены.')
insert into Steps(StepName) values ('Заверните блинчик.')
insert into Steps(StepName) values ('Закрываем крышкой и позволяем блюду потомиться еще 15 мин, напитаться ароматами.')
insert into Steps(StepName) values ('Залейте масло. Возьмите половник и зачерпните тесто несколько раз.')
insert into Steps(StepName) values ('Заливаем горячим маслом морковку.')
insert into Steps(StepName) values ('Заливаем смесью мясо и овощи.')
insert into Steps(StepName) values ('Заправьте мясной начинкой.')
insert into Steps(StepName) values ('Засыпать сахаром.')
insert into Steps(StepName) values ('Затем воду слить, лимон убрать. Айву очистить от кожуры (она легко снимется) и нарезать небольшими кубиками.')
insert into Steps(StepName) values ('Затем выложите мясо, перемешайте и обжаривайте несколько минут на среднем огне, а затем убавьте огонь до минимума и готовьте 10-15 минут.')
insert into Steps(StepName) values ('Затем вынуть мармелад из формы, нарезать на квадратики (или другой формы) обвалять в сахаре.')
insert into Steps(StepName) values ('Затем добавьте томатную пасту, соль, перец. Перемешайте, накройте крышкой и готовьте на среднем огне в течение 30 минут.')
insert into Steps(StepName) values ('Затем на лаваш с сыром выложить сосиску.')
insert into Steps(StepName) values ('Затем порежьте эти пластины на тонкие полосочки (соломку).')
insert into Steps(StepName) values ('Затем снять с огня, протереть через сито или пюрировать блендером в однородную массу. Снова поставить на плиту и варить 15-20 минут на медленном огне, постоянно помешивая.')
insert into Steps(StepName) values ('Затем тесто обмять и оставить в теплом месте еще на 30 минут.Айву вымыть, удалить сердцевину и нарезать небольшими кусочками.')
insert into Steps(StepName) values ('И так продолжать варить 4 суток.')
insert into Steps(StepName) values ('Ингредиенты для морковки по-корейски.')
insert into Steps(StepName) values ('К взбитым белкам добавить мучную массу, ванильный порошок по вкусу и творог - всё тщательно смешать.')
insert into Steps(StepName) values ('К полученной массе добавляем 20 мл. воды. Необходимо вымесить твёрдое тесто. Если тесто липкое, советую его положить на некоторое время в холодильник.')
insert into Steps(StepName) values ('К полученной однородной массе добавить цедру одного лимона и хорошо перемешать.')
insert into Steps(StepName) values ('Классический бефстроганов готов!')
insert into Steps(StepName) values ('Когда тесто подойдет, посыпать поверх начинки крошкой и поставить пирог с айвой в разогретую до 200 градусов духовку на 25-30 минут. Теста получается немного больше, чем требуется для формы диаметром 25 см. Из остатков теста можно приготовить пирожки или булочки.')
insert into Steps(StepName) values ('Кожуру оставить.')
insert into Steps(StepName) values ('Края лаваша подогнуть и свернуть рулетом. Таким образом подготовить все рулетики.')
insert into Steps(StepName) values ('Куриное филе порежьте на небольшие по размеру пластины толщиной 5-6 мм. и обжарьте в небольшом количестве растительного масла до золотистой корочки. Идеально, если вы будете жарить их на гриле.')
insert into Steps(StepName) values ('Куриное филе порезать небольшими кусочками, посолить, посыпать специями, обжарить на растительном масле в течение 5-7 минут на среднем огне.')
insert into Steps(StepName) values ('Лаваш порезать на прямоугольники, размером приблизительно 15х20 см.')
insert into Steps(StepName) values ('Лаваш разрезать на прямоугольники длиной около 20 сантиментов и шириной немного больше, чем длина сосиски')
insert into Steps(StepName) values ('Лук порежьте тонкими полукольцами или четвертькольцами, если лук крупный.')
insert into Steps(StepName) values ('Лук чистим, перец очищаем от зерен.')
insert into Steps(StepName) values ('Мармелад из айвы готов.')
insert into Steps(StepName) values ('Можно и кубиком мелким порезать.')
insert into Steps(StepName) values ('Можно переложить варенье в баночку, вазочку.')
insert into Steps(StepName) values ('Морковь чистим, натираем на крупную терку.')
insert into Steps(StepName) values ('Мясо без труда нарезается тоненькими кусочками.')
insert into Steps(StepName) values ('Мясо готово.')
insert into Steps(StepName) values ('Мясо промыть под проточной водой.')
insert into Steps(StepName) values ('На край лаваша выложить 1-2 столовые ложки начинки. Сверху - майонез (можно еще добавить по желанию любую зелень, сыр).')
insert into Steps(StepName) values ('На сковороде разогрейте растительное масло, выложите лук и обжарьте на среднем огне до золотистого цвета.')
insert into Steps(StepName) values ('Нагреваем сковороду, добавляем масло и выпекаем круглые румяные блинчики.')
insert into Steps(StepName) values ('Нагрейте сковороду до средне-высокой температуры, налейте масло и положите мясной фарш.')
insert into Steps(StepName) values ('Накройте крышкой и готовьте в течении 20 минут.')
insert into Steps(StepName) values ('Накройте крышкой и тушите еще 5 минут.')
insert into Steps(StepName) values ('Налейте подсолнечное масло и водку.')
insert into Steps(StepName) values ('Нарежьте мясо тоненькими кусочками.')
insert into Steps(StepName) values ('Нарезаем лук крупно. Обжариваем лучок в растительном масле до золотистого цвета.')
insert into Steps(StepName) values ('Нарезать кубиками.')
insert into Steps(StepName) values ('Нарезать на четвертинки, очистить от семечек.')
insert into Steps(StepName) values ('Натираем морковь длинной соломкой с помощью специальной терки.')
insert into Steps(StepName) values ('Начинка готова. Дать ей остыть.')
insert into Steps(StepName) values ('Начинку размещаем внутри выпеченной основы.')
insert into Steps(StepName) values ('Обжариваем вместе с мясом и овощами.')
insert into Steps(StepName) values ('Обжарить лаваш на среднем огне со всех сторон до золотистой хрустящей корочки (примерно, по 2 минуты с каждой стороны).')
insert into Steps(StepName) values ('Обжарить лаваш с начинкой на сковороде, в достаточном количестве растительного масла, с двух сторон до румяного цвета (около 3-4 минут с каждой стороны).')
insert into Steps(StepName) values ('Обмакните бумажными полотенцами.')
insert into Steps(StepName) values ('Овощи нарезаем кубиками.')
insert into Steps(StepName) values ('Оставьте в сторону на 15 минут.')
insert into Steps(StepName) values ('Отправьте в сковороду муку и хорошенько перемешайте, чтобы она равномерно распределилась.')
insert into Steps(StepName) values ('Отставить в сторонку.')
insert into Steps(StepName) values ('Пакет хорошо завяжите.')
insert into Steps(StepName) values ('Перед подачей на стол дайте морковке постоять в холодильнике примерно 2-3 часа.')
insert into Steps(StepName) values ('Перемешать руками в крошку, убрать в холодильник.')
insert into Steps(StepName) values ('Перемешиваем.')
insert into Steps(StepName) values ('Плавленый сыр натереть на терке и разровнять по поверхности лаваша.')
insert into Steps(StepName) values ('По истечении 20 минут, взбейте 1 яйцо с небольшим количеством воды.')
insert into Steps(StepName) values ('Подавайте с картофельным пюре')
insert into Steps(StepName) values ('Подавать в горячем виде.')
insert into Steps(StepName) values ('Подготовьте все необходимые ингредиенты.')
insert into Steps(StepName) values ('Подготовьте все необходимые ингредиенты. Яйца отварите вкрутую.')
insert into Steps(StepName) values ('Подготовьте заправку: смешайте в небольшой креманке свежевыжатый лимонный сок, горчицу и немного оливкового масла. Полейте готовой смесью салат, присыпьте кунжутными семечками. Они хоть и не входят в классический вариант салата «Цезарь», очень хорошо сочетаются с овощами и придают салату пикантность. Подавайте салат в качестве закуски перед основным блюдом или в качестве главного блюда.')
insert into Steps(StepName) values ('Подготовьте ингредиенты.')
insert into Steps(StepName) values ('Позволить маслу нагреться, тогда обжаривать мясо со всех сторон в течение 20 минут.')
insert into Steps(StepName) values ('Помидор очистите и порежьте нетолстыми дольками.')
insert into Steps(StepName) values ('После 4-ой варки варенье из айвы готово и выглядит оно замечательно, и на вкус приятно.')
insert into Steps(StepName) values ('После 5 минут обжарки, добавьте воды и уменьшите огонь до средне-низкого уровня.')
insert into Steps(StepName) values ('После этого добавить в сковороду порезанную тонкими брусочками колбасу и соломкой - болгарский перец.')
insert into Steps(StepName) values ('Поставить пирог в духовой шкаф и выпекать до золотистой корочки при температуре 180 гр.')
insert into Steps(StepName) values ('Приготавливаем соус: смешиваем воду, со сметаной, томатной пастой и мукой. Все хорошо перемешиваем при помощи венчика.')
insert into Steps(StepName) values ('Приготовить айву.')
insert into Steps(StepName) values ('Проварить 2 минуты, выключить.')
insert into Steps(StepName) values ('Разбейте 3 яйца в миску с теплым молоком.')
insert into Steps(StepName) values ('Сам лаваш получается хрустящим, а внутри сочная и очень вкусная начинка.')
insert into Steps(StepName) values ('Свернуть лаваш в рулет.')
insert into Steps(StepName) values ('Сложить айву в кастрюлю для варки варенья.')
insert into Steps(StepName) values ('Сложить в кастрюлю, влить 500 мл воды, довести до кипения и варить 20-30 минут до мягкости айвы.')
insert into Steps(StepName) values ('Смазать лаваш смесью майонеза, кетчупа и горчицы (количество регулируем под свой вкус).')
insert into Steps(StepName) values ('Смешайте венчиком или миксером.')
insert into Steps(StepName) values ('Смешать муку и дрожжи, постепенно соединить сухие и жидкие ингредиенты. Замесить мягкое тесто, накрыть полотенцем и убрать для подхода на 1 час в теплое место.')
insert into Steps(StepName) values ('Смешиваем.')
insert into Steps(StepName) values ('Соберите салат. На дно тарелки положите промытые листья салата, сверху положите помидоры, сухарики, порезанные дольками яйца и кусочки курицы.')
insert into Steps(StepName) values ('Сосиски в лаваше выложить на разогретую с растительным маслом сковороду.')
insert into Steps(StepName) values ('Сосиски в лаваше, приготовленные по этому простому рецепту, станут отличным перекусом.')
insert into Steps(StepName) values ('Спустя 3 дня готовое мясо достаньте из маринада, не ополаскивайте.')
insert into Steps(StepName) values ('Сразу же добавьте нарезанный лук.')
insert into Steps(StepName) values ('Сюда же добавить и помидор, порезанный небольшими кубиками.')
insert into Steps(StepName) values ('Такой мармелад можно хранить в закрытой сухой стеклянной посуде всю зиму.')
insert into Steps(StepName) values ('Творожный чизкейк готов. Подавать охлаждённым, блюдо можно украсить шариками мороженного, покрытыми тёртым шоколадом.')
insert into Steps(StepName) values ('Тесто выложить на дно формы, сделать бортики. Выложить начинку и оставить подходить на 20 минут.')
insert into Steps(StepName) values ('Тесто выпекаем в духовом шкафу 8-10 минут при температуре 180 градусов.')
insert into Steps(StepName) values ('Тушите мясо до мягкости. Соус должен стать однородным и достаточно густым, чтобы не стекал с ложки.')
insert into Steps(StepName) values ('Тушить все на небольшом огне около 10 минут.')
insert into Steps(StepName) values ('Тщательно всё перемешайте внутри пакета.')
insert into Steps(StepName) values ('Тщательно протереть тряпочкой всю ее поверхность, чтобы убрать невидимый пушок из ворсинок.')
insert into Steps(StepName) values ('Уберите мясо в холодильник на 3 дня.')
insert into Steps(StepName) values ('Убираем лук из сковороды.')
insert into Steps(StepName) values ('Убираем масло с огня и добавляем уксус.')
insert into Steps(StepName) values ('Уложите мясо в пакет.')
insert into Steps(StepName) values ('Хлеб порежьте на небольшие кубики и подсушите в духовке или микроволновке.')
insert into Steps(StepName) values ('Хорошо помешайте.')
insert into Steps(StepName) values ('Через сутки повторить варку.')
insert into Steps(StepName) values ('Я готовила три порции и у меня получились вот такие три рулета.')
insert into Steps(StepName) values ('Яйцо взбить с сахаром, ванильным сахаром и солью, добавить сметану, мягкое масло, перемешать.')