--Создаем скрипт для занесения в таблицу Ingredients--
insert into Ingredients (Name) values ('айва')
insert into Ingredients (Name) values ('вода')
insert into Ingredients (Name) values ('водка')
insert into Ingredients (Name) values ('говядина')
insert into Ingredients (Name) values ('горчица')
insert into Ingredients (Name) values ('дрожжи сухие')
insert into Ingredients (Name) values ('зелень')
insert into Ingredients (Name) values ('изюм')
insert into Ingredients (Name) values ('кетчуп')
insert into Ingredients (Name) values ('колбаса')
insert into Ingredients (Name) values ('лаваш')
insert into Ingredients (Name) values ('лимон')
insert into Ingredients (Name) values ('листья салата')
insert into Ingredients (Name) values ('лук репчатый')
insert into Ingredients (Name) values ('майонез')
insert into Ingredients (Name) values ('малина')
insert into Ingredients (Name) values ('масло оливковое')
insert into Ingredients (Name) values ('масло подсолнечное')
insert into Ingredients (Name) values ('масло растительное для жарки')
insert into Ingredients (Name) values ('масло сливочное')
insert into Ingredients (Name) values ('мед жидкий')
insert into Ingredients (Name) values ('молоко')
insert into Ingredients (Name) values ('морковь')
insert into Ingredients (Name) values ('мука')
insert into Ingredients (Name) values ('орехи грецкие')
insert into Ingredients (Name) values ('паста томатная')
insert into Ingredients (Name) values ('перец болгарский сладкий')
insert into Ingredients (Name) values ('перец душистый молотый')
insert into Ingredients (Name) values ('перец красный молотый')
insert into Ingredients (Name) values ('перец черный молотый')
insert into Ingredients (Name) values ('помидор')
insert into Ingredients (Name) values ('помидор свежий')
insert into Ingredients (Name) values ('порошок ванильный')
insert into Ingredients (Name) values ('пудра сахарная')
insert into Ingredients (Name) values ('рис отварной')
insert into Ingredients (Name) values ('розмарин')
insert into Ingredients (Name) values ('сахар')
insert into Ingredients (Name) values ('сахар ванильный')
insert into Ingredients (Name) values ('сахар коричневый')
insert into Ingredients (Name) values ('семечки кунжутные')
insert into Ingredients (Name) values ('сливки (33%)')
insert into Ingredients (Name) values ('смесь перцев')
insert into Ingredients (Name) values ('сметана')
insert into Ingredients (Name) values ('сок лимонный')
insert into Ingredients (Name) values ('соль')
insert into Ingredients (Name) values ('сосиски')
insert into Ingredients (Name) values ('соус соевый')
insert into Ingredients (Name) values ('специи')
insert into Ingredients (Name) values ('специи для курицы')
insert into Ingredients (Name) values ('сыр плавленый')
insert into Ingredients (Name) values ('творог')
insert into Ingredients (Name) values ('тмин')
insert into Ingredients (Name) values ('уксус яблочный')
insert into Ingredients (Name) values ('фарш говяжий')
insert into Ingredients (Name) values ('филе куриное')
insert into Ingredients (Name) values ('хлеб белый')
insert into Ingredients (Name) values ('хлопья миндальные')
insert into Ingredients (Name) values ('хлопья овсяные')
insert into Ingredients (Name) values ('чеснок')
insert into Ingredients (Name) values ('щепотка соли')
insert into Ingredients (Name) values ('яйцо')