--—оздаем скрипт дл€ занесени€ в таблицу Ingredients--
insert into Ingredients (NameIngredient) values ('айва')
insert into Ingredients (NameIngredient) values ('вода')
insert into Ingredients (NameIngredient) values ('водка')
insert into Ingredients (NameIngredient) values ('гов€дина')
insert into Ingredients (NameIngredient) values ('горчица')
insert into Ingredients (NameIngredient) values ('дрожжи сухие')
insert into Ingredients (NameIngredient) values ('зелень')
insert into Ingredients (NameIngredient) values ('изюм')
insert into Ingredients (NameIngredient) values ('кетчуп')
insert into Ingredients (NameIngredient) values ('колбаса')
insert into Ingredients (NameIngredient) values ('лаваш')
insert into Ingredients (NameIngredient) values ('лимон')
insert into Ingredients (NameIngredient) values ('листь€ салата')
insert into Ingredients (NameIngredient) values ('лук репчатый')
insert into Ingredients (NameIngredient) values ('майонез')
insert into Ingredients (NameIngredient) values ('малина')
insert into Ingredients (NameIngredient) values ('масло оливковое')
insert into Ingredients (NameIngredient) values ('масло подсолнечное')
insert into Ingredients (NameIngredient) values ('масло растительное дл€ жарки')
insert into Ingredients (NameIngredient) values ('масло сливочное')
insert into Ingredients (NameIngredient) values ('мед жидкий')
insert into Ingredients (NameIngredient) values ('молоко')
insert into Ingredients (NameIngredient) values ('морковь')
insert into Ingredients (NameIngredient) values ('мука')
insert into Ingredients (NameIngredient) values ('орехи грецкие')
insert into Ingredients (NameIngredient) values ('паста томатна€')
insert into Ingredients (NameIngredient) values ('перец болгарский сладкий')
insert into Ingredients (NameIngredient) values ('перец душистый молотый')
insert into Ingredients (NameIngredient) values ('перец красный молотый')
insert into Ingredients (NameIngredient) values ('перец черный молотый')
insert into Ingredients (NameIngredient) values ('помидор')
insert into Ingredients (NameIngredient) values ('помидор свежий')
insert into Ingredients (NameIngredient) values ('порошок ванильный')
insert into Ingredients (NameIngredient) values ('пудра сахарна€')
insert into Ingredients (NameIngredient) values ('рис отварной')
insert into Ingredients (NameIngredient) values ('розмарин')
insert into Ingredients (NameIngredient) values ('сахар')
insert into Ingredients (NameIngredient) values ('сахар ванильный')
insert into Ingredients (NameIngredient) values ('сахар коричневый')
insert into Ingredients (NameIngredient) values ('семечки кунжутные')
insert into Ingredients (NameIngredient) values ('сливки (33%)')
insert into Ingredients (NameIngredient) values ('смесь перцев')
insert into Ingredients (NameIngredient) values ('сметана')
insert into Ingredients (NameIngredient) values ('сок лимонный')
insert into Ingredients (NameIngredient) values ('соль')
insert into Ingredients (NameIngredient) values ('сосиски')
insert into Ingredients (NameIngredient) values ('соус соевый')
insert into Ingredients (NameIngredient) values ('специи')
insert into Ingredients (NameIngredient) values ('специи дл€ курицы')
insert into Ingredients (NameIngredient) values ('сыр плавленый')
insert into Ingredients (NameIngredient) values ('творог')
insert into Ingredients (NameIngredient) values ('тмин')
insert into Ingredients (NameIngredient) values ('уксус €блочный')
insert into Ingredients (NameIngredient) values ('фарш гов€жий')
insert into Ingredients (NameIngredient) values ('филе куриное')
insert into Ingredients (NameIngredient) values ('хлеб белый')
insert into Ingredients (NameIngredient) values ('хлопь€ миндальные')
insert into Ingredients (NameIngredient) values ('хлопь€ овс€ные')
insert into Ingredients (NameIngredient) values ('чеснок')
insert into Ingredients (NameIngredient) values ('щепотка соли')
insert into Ingredients (NameIngredient) values ('€йцо')