--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(1,11)
insert into RecipeIngredient(RecipeId, IngredientId) values(1,55)
insert into RecipeIngredient(RecipeId, IngredientId) values(1,10)
insert into RecipeIngredient(RecipeId, IngredientId) values(1,27)
insert into RecipeIngredient(RecipeId, IngredientId) values(1,14)
insert into RecipeIngredient(RecipeId, IngredientId) values(1,32)
insert into RecipeIngredient(RecipeId, IngredientId) values(1,45)
insert into RecipeIngredient(RecipeId, IngredientId) values(1,49)
insert into RecipeIngredient(RecipeId, IngredientId) values(1,59)
insert into RecipeIngredient(RecipeId, IngredientId) values(1,19)
insert into RecipeIngredient(RecipeId, IngredientId) values(1,15)

--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(2,11)
insert into RecipeIngredient(RecipeId, IngredientId) values(2,9)
insert into RecipeIngredient(RecipeId, IngredientId) values(2,5)
insert into RecipeIngredient(RecipeId, IngredientId) values(2,15)
insert into RecipeIngredient(RecipeId, IngredientId) values(2,50)
insert into RecipeIngredient(RecipeId, IngredientId) values(2,46)
insert into RecipeIngredient(RecipeId, IngredientId) values(2,19)

--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(3,1)
insert into RecipeIngredient(RecipeId, IngredientId) values(3,37)
insert into RecipeIngredient(RecipeId, IngredientId) values(3,2)

--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(4,1)
insert into RecipeIngredient(RecipeId, IngredientId) values(4,37)
insert into RecipeIngredient(RecipeId, IngredientId) values(4,2)

--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(5,22)
insert into RecipeIngredient(RecipeId, IngredientId) values(5,43)
insert into RecipeIngredient(RecipeId, IngredientId) values(5,61)
insert into RecipeIngredient(RecipeId, IngredientId) values(5,20)
insert into RecipeIngredient(RecipeId, IngredientId) values(5,37)
insert into RecipeIngredient(RecipeId, IngredientId) values(5,38)
insert into RecipeIngredient(RecipeId, IngredientId) values(5,60)
insert into RecipeIngredient(RecipeId, IngredientId) values(5,24)
insert into RecipeIngredient(RecipeId, IngredientId) values(5,6)

--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(6,22)
insert into RecipeIngredient(RecipeId, IngredientId) values(6,61)
insert into RecipeIngredient(RecipeId, IngredientId) values(6,45)
insert into RecipeIngredient(RecipeId, IngredientId) values(6,24)
insert into RecipeIngredient(RecipeId, IngredientId) values(6,18)
insert into RecipeIngredient(RecipeId, IngredientId) values(6,54)
insert into RecipeIngredient(RecipeId, IngredientId) values(6,52)
insert into RecipeIngredient(RecipeId, IngredientId) values(6,30)
insert into RecipeIngredient(RecipeId, IngredientId) values(6,2)
insert into RecipeIngredient(RecipeId, IngredientId) values(6,20)

--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(7,4)
insert into RecipeIngredient(RecipeId, IngredientId) values(7,2)
insert into RecipeIngredient(RecipeId, IngredientId) values(7,45)
insert into RecipeIngredient(RecipeId, IngredientId) values(7,37)
insert into RecipeIngredient(RecipeId, IngredientId) values(7,30)
insert into RecipeIngredient(RecipeId, IngredientId) values(7,18)

--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(8,4)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,14)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,27)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,26)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,43)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,24)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,23)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,2)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,7)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,45)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,29)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,48)
insert into RecipeIngredient(RecipeId, IngredientId) values(8,19)

--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(9,4)
insert into RecipeIngredient(RecipeId, IngredientId) values(9,14)
insert into RecipeIngredient(RecipeId, IngredientId) values(9,43)
insert into RecipeIngredient(RecipeId, IngredientId) values(9,26)
insert into RecipeIngredient(RecipeId, IngredientId) values(9,24)
insert into RecipeIngredient(RecipeId, IngredientId) values(9,45)
insert into RecipeIngredient(RecipeId, IngredientId) values(9,29)

--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(10,24)
insert into RecipeIngredient(RecipeId, IngredientId) values(10,37)
insert into RecipeIngredient(RecipeId, IngredientId) values(10,20)
insert into RecipeIngredient(RecipeId, IngredientId) values(10,2)
insert into RecipeIngredient(RecipeId, IngredientId) values(10,61)
insert into RecipeIngredient(RecipeId, IngredientId) values(10,51)
insert into RecipeIngredient(RecipeId, IngredientId) values(10,33)
insert into RecipeIngredient(RecipeId, IngredientId) values(10,12)
insert into RecipeIngredient(RecipeId, IngredientId) values(10,45)

--Заполняем таблицу RecipeIngredient
insert into RecipeIngredient(RecipeId, IngredientId) values(11,23)
insert into RecipeIngredient(RecipeId, IngredientId) values(11,14)
insert into RecipeIngredient(RecipeId, IngredientId) values(11,19)
insert into RecipeIngredient(RecipeId, IngredientId) values(11,53)
insert into RecipeIngredient(RecipeId, IngredientId) values(11,37)
insert into RecipeIngredient(RecipeId, IngredientId) values(11,59)
insert into RecipeIngredient(RecipeId, IngredientId) values(11,29)
insert into RecipeIngredient(RecipeId, IngredientId) values(11,45)

insert into RecipeIngredient(RecipeId, IngredientId) values(12,55)
insert into RecipeIngredient(RecipeId, IngredientId) values(12,31)
insert into RecipeIngredient(RecipeId, IngredientId) values(12,61)
insert into RecipeIngredient(RecipeId, IngredientId) values(12,56)
insert into RecipeIngredient(RecipeId, IngredientId) values(12,13)
insert into RecipeIngredient(RecipeId, IngredientId) values(12,17)
insert into RecipeIngredient(RecipeId, IngredientId) values(12,44)
insert into RecipeIngredient(RecipeId, IngredientId) values(12,5)
insert into RecipeIngredient(RecipeId, IngredientId) values(12,40)
