--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(1,73)
insert into RecipeStep(RecipeId, StepId) values(1,32)
insert into RecipeStep(RecipeId, StepId) values(1,124)
insert into RecipeStep(RecipeId, StepId) values(1,143)
insert into RecipeStep(RecipeId, StepId) values(1,149)
insert into RecipeStep(RecipeId, StepId) values(1,8)
insert into RecipeStep(RecipeId, StepId) values(1,4)
insert into RecipeStep(RecipeId, StepId) values(1,98)
insert into RecipeStep(RecipeId, StepId) values(1,75)
insert into RecipeStep(RecipeId, StepId) values(1,86)
insert into RecipeStep(RecipeId, StepId) values(1,72)
insert into RecipeStep(RecipeId, StepId) values(1,102)
insert into RecipeStep(RecipeId, StepId) values(1,46)
insert into RecipeStep(RecipeId, StepId) values(1,130)

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(2,76)
insert into RecipeStep(RecipeId, StepId) values(2,134)
insert into RecipeStep(RecipeId, StepId) values(2,112)
insert into RecipeStep(RecipeId, StepId) values(2,60)
insert into RecipeStep(RecipeId, StepId) values(2,131)
insert into RecipeStep(RecipeId, StepId) values(2,159)
insert into RecipeStep(RecipeId, StepId) values(2,139)
insert into RecipeStep(RecipeId, StepId) values(2,101)
insert into RecipeStep(RecipeId, StepId) values(2,140)
insert into RecipeStep(RecipeId, StepId) values(2,115)
--Сосиски в лаваше конец--

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(3,127)
insert into RecipeStep(RecipeId, StepId) values(3,151)
insert into RecipeStep(RecipeId, StepId) values(3,96)
insert into RecipeStep(RecipeId, StepId) values(3,71)
insert into RecipeStep(RecipeId, StepId) values(3,132)
insert into RecipeStep(RecipeId, StepId) values(3,55)
insert into RecipeStep(RecipeId, StepId) values(3,43)
insert into RecipeStep(RecipeId, StepId) values(3,42)
insert into RecipeStep(RecipeId, StepId) values(3,128)
insert into RecipeStep(RecipeId, StepId) values(3,105)
insert into RecipeStep(RecipeId, StepId) values(3,158)
insert into RecipeStep(RecipeId, StepId) values(3,41)
insert into RecipeStep(RecipeId, StepId) values(3,64)
insert into RecipeStep(RecipeId, StepId) values(3,123)
insert into RecipeStep(RecipeId, StepId) values(3,81)
--конец--

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(4,22)
insert into RecipeStep(RecipeId, StepId) values(4,133)
insert into RecipeStep(RecipeId, StepId) values(4,2)
insert into RecipeStep(RecipeId, StepId) values(4,56)
insert into RecipeStep(RecipeId, StepId) values(4,21)
insert into RecipeStep(RecipeId, StepId) values(4,7)
insert into RecipeStep(RecipeId, StepId) values(4,12)
insert into RecipeStep(RecipeId, StepId) values(4,62)
insert into RecipeStep(RecipeId, StepId) values(4,24)
insert into RecipeStep(RecipeId, StepId) values(4,58)
--конец--

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(5,159)
insert into RecipeStep(RecipeId, StepId) values(5,16)
insert into RecipeStep(RecipeId, StepId) values(5,136)
insert into RecipeStep(RecipeId, StepId) values(5,63)
insert into RecipeStep(RecipeId, StepId) values(5,1)
insert into RecipeStep(RecipeId, StepId) values(5,9)
insert into RecipeStep(RecipeId, StepId) values(5,15)
insert into RecipeStep(RecipeId, StepId) values(5,29)
insert into RecipeStep(RecipeId, StepId) values(5,35)
insert into RecipeStep(RecipeId, StepId) values(5,110)
insert into RecipeStep(RecipeId, StepId) values(5,70)
insert into RecipeStep(RecipeId, StepId) values(5,26)
--конец--

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(6,129)
insert into RecipeStep(RecipeId, StepId) values(6,38)
insert into RecipeStep(RecipeId, StepId) values(6,135)
insert into RecipeStep(RecipeId, StepId) values(6,35)
insert into RecipeStep(RecipeId, StepId) values(6,51)
insert into RecipeStep(RecipeId, StepId) values(6,105)
insert into RecipeStep(RecipeId, StepId) values(6,89)
insert into RecipeStep(RecipeId, StepId) values(6,142)
insert into RecipeStep(RecipeId, StepId) values(6,39)
insert into RecipeStep(RecipeId, StepId) values(6,157)
insert into RecipeStep(RecipeId, StepId) values(6,123)
insert into RecipeStep(RecipeId, StepId) values(6,90)
insert into RecipeStep(RecipeId, StepId) values(6,113)
insert into RecipeStep(RecipeId, StepId) values(6,40)
insert into RecipeStep(RecipeId, StepId) values(6,88)
insert into RecipeStep(RecipeId, StepId) values(6,36)
insert into RecipeStep(RecipeId, StepId) values(6,54)
insert into RecipeStep(RecipeId, StepId) values(6,49)
--конец--

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(7,119)
insert into RecipeStep(RecipeId, StepId) values(7,17)
insert into RecipeStep(RecipeId, StepId) values(7,6)
insert into RecipeStep(RecipeId, StepId) values(7,92)
insert into RecipeStep(RecipeId, StepId) values(7,150)
insert into RecipeStep(RecipeId, StepId) values(7,155)
insert into RecipeStep(RecipeId, StepId) values(7,108)
insert into RecipeStep(RecipeId, StepId) values(7,152)
insert into RecipeStep(RecipeId, StepId) values(7,10)
insert into RecipeStep(RecipeId, StepId) values(7,141)
insert into RecipeStep(RecipeId, StepId) values(7,103)
insert into RecipeStep(RecipeId, StepId) values(7,93)
insert into RecipeStep(RecipeId, StepId) values(7,84)
insert into RecipeStep(RecipeId, StepId) values(7,3)
insert into RecipeStep(RecipeId, StepId) values(7,83)
--конец--

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(8,85)
insert into RecipeStep(RecipeId, StepId) values(8,95)
insert into RecipeStep(RecipeId, StepId) values(8,14)
insert into RecipeStep(RecipeId, StepId) values(8,120)
insert into RecipeStep(RecipeId, StepId) values(8,78)
insert into RecipeStep(RecipeId, StepId) values(8,104)
insert into RecipeStep(RecipeId, StepId) values(8,33)
insert into RecipeStep(RecipeId, StepId) values(8,19)
insert into RecipeStep(RecipeId, StepId) values(8,82)
insert into RecipeStep(RecipeId, StepId) values(8,100)
insert into RecipeStep(RecipeId, StepId) values(8,126)
insert into RecipeStep(RecipeId, StepId) values(8,53)
insert into RecipeStep(RecipeId, StepId) values(8,13)
insert into RecipeStep(RecipeId, StepId) values(8,50)
--конец--

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(9,116)
insert into RecipeStep(RecipeId, StepId) values(9,23)
insert into RecipeStep(RecipeId, StepId) values(9,61)
insert into RecipeStep(RecipeId, StepId) values(9,77)
insert into RecipeStep(RecipeId, StepId) values(9,81)
insert into RecipeStep(RecipeId, StepId) values(9,87)
insert into RecipeStep(RecipeId, StepId) values(9,57)
insert into RecipeStep(RecipeId, StepId) values(9,106)
insert into RecipeStep(RecipeId, StepId) values(9,37)
insert into RecipeStep(RecipeId, StepId) values(9,59)
insert into RecipeStep(RecipeId, StepId) values(9,44)
insert into RecipeStep(RecipeId, StepId) values(9,148)
insert into RecipeStep(RecipeId, StepId) values(9,69)
insert into RecipeStep(RecipeId, StepId) values(9,114)

--конец--

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(10,30)
insert into RecipeStep(RecipeId, StepId) values(10,20)
insert into RecipeStep(RecipeId, StepId) values(10,67)
insert into RecipeStep(RecipeId, StepId) values(10,11)
insert into RecipeStep(RecipeId, StepId) values(10,25)
insert into RecipeStep(RecipeId, StepId) values(10,146)
insert into RecipeStep(RecipeId, StepId) values(10,28)
insert into RecipeStep(RecipeId, StepId) values(10,47)
insert into RecipeStep(RecipeId, StepId) values(10,48)
insert into RecipeStep(RecipeId, StepId) values(10,5)
insert into RecipeStep(RecipeId, StepId) values(10,99)
insert into RecipeStep(RecipeId, StepId) values(10,125)
insert into RecipeStep(RecipeId, StepId) values(10,145)
--конец--

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(11,65)
insert into RecipeStep(RecipeId, StepId) values(11,97)
insert into RecipeStep(RecipeId, StepId) values(11,45)
insert into RecipeStep(RecipeId, StepId) values(11,34)
insert into RecipeStep(RecipeId, StepId) values(11,137)
insert into RecipeStep(RecipeId, StepId) values(11,94)
insert into RecipeStep(RecipeId, StepId) values(11,153)
insert into RecipeStep(RecipeId, StepId) values(11,154)
insert into RecipeStep(RecipeId, StepId) values(11,52)
insert into RecipeStep(RecipeId, StepId) values(11,111)
insert into RecipeStep(RecipeId, StepId) values(11,109)
--конец--

--Заполняем таблицу RecipeStep
insert into RecipeStep(RecipeId, StepId) values(12,117)
insert into RecipeStep(RecipeId, StepId) values(12,73)
insert into RecipeStep(RecipeId, StepId) values(12,156)
insert into RecipeStep(RecipeId, StepId) values(12,121)
insert into RecipeStep(RecipeId, StepId) values(12,138)
insert into RecipeStep(RecipeId, StepId) values(12,118)
--конец--